// What each commissioner action reads as in the league's log (commish_log, migration 110). The database records the
// function a commissioner used; this is the line GMs see.
export const COMMISH_ACTIONS: Record<string, { emoji: string; text: string }> = {
  commish_add_spectator: { emoji: '🍿', text: 'added a spectator' },
  commish_bill_entries: { emoji: '🧾', text: 'billed the season’s entries' },
  commish_coins: { emoji: '🪙', text: 'gave or took coins' },
  commish_delete_line: { emoji: '🧾', text: 'removed a money line' },
  commish_fund_entry: { emoji: '📈', text: 'recorded a fund entry' },
  commish_fund_price: { emoji: '📈', text: 'set the fund’s price' },
  commish_fund_settings: { emoji: '📈', text: 'changed the fund’s settings' },
  commish_market: { emoji: '📖', text: 'opened or changed a Book market' },
  commish_money_line: { emoji: '💵', text: 'added a money line' },
  commish_move_player: { emoji: '🔁', text: 'moved a player between teams' },
  commish_post_payouts: { emoji: '🏆', text: 'posted the payouts' },
  commish_reset_password: { emoji: '🔑', text: 'reset a GM’s password' },
  commish_rule_bet: { emoji: '⚖️', text: 'ruled on a side bet' },
  commish_set_brand: { emoji: '🎨', text: 'changed the league’s name or look' },
  commish_set_cocommish: { emoji: '🛡️', text: 'changed who runs the league' },
  commish_set_keeper: { emoji: '🔒', text: 'changed a keeper' },
  commish_set_keepers: { emoji: '🔒', text: 'set a team’s keepers' },
  commish_set_login_email: { emoji: '✉️', text: 'changed a GM’s sign-in email' },
  commish_set_pick_owner: { emoji: '📋', text: 'moved a draft pick' },
  commish_set_spectator: { emoji: '🍿', text: 'changed a spectator’s access' },
  commish_settle_bet: { emoji: '⚖️', text: 'settled a side bet' },
  commish_settle_market: { emoji: '📖', text: 'settled a Book market' },
  commish_settle_team: { emoji: '💵', text: 'settled up with a GM' },
  commish_update_league: { emoji: '⚙️', text: 'changed the league settings' },
  commish_update_scoring: { emoji: '📐', text: 'changed the scoring' },
  commish_vacate_seat: { emoji: '🪑', text: 'handed a team to a new GM' },
  draft_pause: { emoji: '⏸️', text: 'paused the draft' },
  draft_randomize_order: { emoji: '🎲', text: 'drew the draft order' },
  draft_reset: { emoji: '↩️', text: 'reset the draft' },
  draft_resume: { emoji: '▶️', text: 'resumed the draft' },
  draft_set_order: { emoji: '📋', text: 'set the draft order' },
  draft_start: { emoji: '🟢', text: 'started the draft' },
  draft_undo: { emoji: '↩️', text: 'undid a draft pick' },
  finalize_keepers: { emoji: '🔒', text: 'finalized the keepers' },
  rescore_all: { emoji: '🔄', text: 'rescored the season' },
  review_trade: { emoji: '🤝', text: 'reviewed a trade' },
  close_proposal: { emoji: '🗳️', text: 'closed a rule vote' },
  set_idea_status: { emoji: '💡', text: 'updated a feature idea' },
};
export const commishAction = (a: string) => COMMISH_ACTIONS[a] ?? { emoji: '🛠️', text: a.replace(/^commish_/, '').replace(/_/g, ' ') };
